# resolve-type-names: false

class ::LocaleSetting < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::LocaleSetting, ::LocaleSetting::ActiveRecord_Relation, ::Integer]

  module ::LocaleSetting::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer

    def user_id: () -> ::Integer

    def user_id=: (::Integer) -> ::Integer

    def user_id?: () -> bool

    def user_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def user_id_change: () -> [ ::Integer?, ::Integer? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> ::Integer?

    def user_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def user_id_previous_change: () -> ::Array[::Integer?]?

    def user_id_previously_was: () -> ::Integer?

    def user_id_before_last_save: () -> ::Integer?

    def user_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def user_id_in_database: () -> ::Integer?

    def saved_change_to_user_id: () -> ::Array[::Integer?]?

    def saved_change_to_user_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_user_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void

    def user_id_before_type_cast: () -> ::Integer

    def user_id_for_database: () -> ::Integer

    def preferred_locale: () -> ::String

    def preferred_locale=: (::String | ::Symbol) -> ::String

    def preferred_locale?: () -> bool

    def preferred_locale_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def preferred_locale_change: () -> [ ::String?, ::String? ]

    def preferred_locale_will_change!: () -> void

    def preferred_locale_was: () -> ::String?

    def preferred_locale_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def preferred_locale_previous_change: () -> ::Array[::String?]?

    def preferred_locale_previously_was: () -> ::String?

    def preferred_locale_before_last_save: () -> ::String?

    def preferred_locale_change_to_be_saved: () -> ::Array[::String?]?

    def preferred_locale_in_database: () -> ::String?

    def saved_change_to_preferred_locale: () -> ::Array[::String?]?

    def saved_change_to_preferred_locale?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_preferred_locale?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_preferred_locale!: () -> void

    def clear_preferred_locale_change: () -> void

    def preferred_locale_before_type_cast: () -> ::String

    def preferred_locale_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::LocaleSetting::GeneratedAttributeMethods
  module ::LocaleSetting::GeneratedAliasAttributeMethods
    include ::LocaleSetting::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::LocaleSetting::GeneratedAliasAttributeMethods

  def user: () -> ::User
  def user=: (::User?) -> ::User?
  def reload_user: () -> ::User?
  def build_user: (?untyped) -> ::User
  def create_user: (?untyped) -> ::User
  def create_user!: (?untyped) -> ::User

  module ::LocaleSetting::GeneratedAssociationMethods
  end
  include ::LocaleSetting::GeneratedAssociationMethods

  def en!: () -> bool
  def en?: () -> bool
  def ja!: () -> bool
  def ja?: () -> bool
  def self.preferred_locales: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]
  def self.en: () -> ::LocaleSetting::ActiveRecord_Relation
  def self.not_en: () -> ::LocaleSetting::ActiveRecord_Relation
  def self.ja: () -> ::LocaleSetting::ActiveRecord_Relation
  def self.not_ja: () -> ::LocaleSetting::ActiveRecord_Relation

  module ::LocaleSetting::GeneratedRelationMethods
    def preferred_locales: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]

    def en: () -> ::LocaleSetting::ActiveRecord_Relation

    def not_en: () -> ::LocaleSetting::ActiveRecord_Relation

    def ja: () -> ::LocaleSetting::ActiveRecord_Relation

    def not_ja: () -> ::LocaleSetting::ActiveRecord_Relation
  end

  class ::LocaleSetting::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::LocaleSetting]
    include ::LocaleSetting::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::LocaleSetting, ::Integer]
  end

  class ::LocaleSetting::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::LocaleSetting]
    include ::LocaleSetting::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::LocaleSetting, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::LocaleSetting
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::LocaleSetting]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::LocaleSetting
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::LocaleSetting]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::LocaleSetting
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::LocaleSetting]
    def reload: () -> ::Array[::LocaleSetting]

    def replace: (::Array[::LocaleSetting]) -> void
    def delete: (*::LocaleSetting | ::Integer) -> ::Array[::LocaleSetting]
    def destroy: (*::LocaleSetting | ::Integer) -> ::Array[::LocaleSetting]
    def <<: (*::LocaleSetting | ::Array[::LocaleSetting]) -> self
    def prepend: (*::LocaleSetting | ::Array[::LocaleSetting]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::User < ::ApplicationRecord
end
