# resolve-type-names: false

class ::ProfileBadgesProfile < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::ProfileBadgesProfile, ::ProfileBadgesProfile::ActiveRecord_Relation, top]

  module ::ProfileBadgesProfile::GeneratedAttributeMethods
    def profile_badge_id: () -> ::Integer

    def profile_badge_id=: (::Integer) -> ::Integer

    def profile_badge_id?: () -> bool

    def profile_badge_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def profile_badge_id_change: () -> [ ::Integer?, ::Integer? ]

    def profile_badge_id_will_change!: () -> void

    def profile_badge_id_was: () -> ::Integer?

    def profile_badge_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def profile_badge_id_previous_change: () -> ::Array[::Integer?]?

    def profile_badge_id_previously_was: () -> ::Integer?

    def profile_badge_id_before_last_save: () -> ::Integer?

    def profile_badge_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def profile_badge_id_in_database: () -> ::Integer?

    def saved_change_to_profile_badge_id: () -> ::Array[::Integer?]?

    def saved_change_to_profile_badge_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_profile_badge_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_profile_badge_id!: () -> void

    def clear_profile_badge_id_change: () -> void

    def profile_badge_id_before_type_cast: () -> ::Integer

    def profile_badge_id_for_database: () -> ::Integer

    def profile_id: () -> ::Integer

    def profile_id=: (::Integer) -> ::Integer

    def profile_id?: () -> bool

    def profile_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def profile_id_change: () -> [ ::Integer?, ::Integer? ]

    def profile_id_will_change!: () -> void

    def profile_id_was: () -> ::Integer?

    def profile_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def profile_id_previous_change: () -> ::Array[::Integer?]?

    def profile_id_previously_was: () -> ::Integer?

    def profile_id_before_last_save: () -> ::Integer?

    def profile_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def profile_id_in_database: () -> ::Integer?

    def saved_change_to_profile_id: () -> ::Array[::Integer?]?

    def saved_change_to_profile_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_profile_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_profile_id!: () -> void

    def clear_profile_id_change: () -> void

    def profile_id_before_type_cast: () -> ::Integer

    def profile_id_for_database: () -> ::Integer
  end
  include ::ProfileBadgesProfile::GeneratedAttributeMethods
  module ::ProfileBadgesProfile::GeneratedAliasAttributeMethods
    include ::ProfileBadgesProfile::GeneratedAttributeMethods
  end
  include ::ProfileBadgesProfile::GeneratedAliasAttributeMethods

  def profile_badge: () -> ::ProfileBadge
  def profile_badge=: (::ProfileBadge?) -> ::ProfileBadge?
  def reload_profile_badge: () -> ::ProfileBadge?
  def build_profile_badge: (?untyped) -> ::ProfileBadge
  def create_profile_badge: (?untyped) -> ::ProfileBadge
  def create_profile_badge!: (?untyped) -> ::ProfileBadge
  def profile: () -> ::Profile
  def profile=: (::Profile?) -> ::Profile?
  def reload_profile: () -> ::Profile?
  def build_profile: (?untyped) -> ::Profile
  def create_profile: (?untyped) -> ::Profile
  def create_profile!: (?untyped) -> ::Profile

  module ::ProfileBadgesProfile::GeneratedAssociationMethods
  end
  include ::ProfileBadgesProfile::GeneratedAssociationMethods

  module ::ProfileBadgesProfile::GeneratedRelationMethods
  end

  class ::ProfileBadgesProfile::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::ProfileBadgesProfile]
    include ::ProfileBadgesProfile::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::ProfileBadgesProfile, top]
  end

  class ::ProfileBadgesProfile::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::ProfileBadgesProfile]
    include ::ProfileBadgesProfile::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::ProfileBadgesProfile, top]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ProfileBadgesProfile
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ProfileBadgesProfile]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ProfileBadgesProfile
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ProfileBadgesProfile]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::ProfileBadgesProfile
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::ProfileBadgesProfile]
    def reload: () -> ::Array[::ProfileBadgesProfile]

    def replace: (::Array[::ProfileBadgesProfile]) -> void
    def delete: (*::ProfileBadgesProfile | top) -> ::Array[::ProfileBadgesProfile]
    def destroy: (*::ProfileBadgesProfile | top) -> ::Array[::ProfileBadgesProfile]
    def <<: (*::ProfileBadgesProfile | ::Array[::ProfileBadgesProfile]) -> self
    def prepend: (*::ProfileBadgesProfile | ::Array[::ProfileBadgesProfile]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::ProfileBadge < ::ApplicationRecord
end
class ::Profile < ::ApplicationRecord
end
