class ProfileBadgesProfile < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[ProfileBadgesProfile, ActiveRecord_Relation, top]

  module GeneratedAttributeMethods
    def profile_badge_id: () -> Integer

    def profile_badge_id=: (Integer) -> Integer

    def profile_badge_id?: () -> bool

    def profile_badge_id_changed?: () -> bool

    def profile_badge_id_change: () -> [ Integer?, Integer? ]

    def profile_badge_id_will_change!: () -> void

    def profile_badge_id_was: () -> Integer?

    def profile_badge_id_previously_changed?: () -> bool

    def profile_badge_id_previous_change: () -> Array[Integer?]?

    def profile_badge_id_previously_was: () -> Integer?

    def profile_badge_id_before_last_save: () -> Integer?

    def profile_badge_id_change_to_be_saved: () -> Array[Integer?]?

    def profile_badge_id_in_database: () -> Integer?

    def saved_change_to_profile_badge_id: () -> Array[Integer?]?

    def saved_change_to_profile_badge_id?: () -> bool

    def will_save_change_to_profile_badge_id?: () -> bool

    def restore_profile_badge_id!: () -> void

    def clear_profile_badge_id_change: () -> void

    def profile_id: () -> Integer

    def profile_id=: (Integer) -> Integer

    def profile_id?: () -> bool

    def profile_id_changed?: () -> bool

    def profile_id_change: () -> [ Integer?, Integer? ]

    def profile_id_will_change!: () -> void

    def profile_id_was: () -> Integer?

    def profile_id_previously_changed?: () -> bool

    def profile_id_previous_change: () -> Array[Integer?]?

    def profile_id_previously_was: () -> Integer?

    def profile_id_before_last_save: () -> Integer?

    def profile_id_change_to_be_saved: () -> Array[Integer?]?

    def profile_id_in_database: () -> Integer?

    def saved_change_to_profile_id: () -> Array[Integer?]?

    def saved_change_to_profile_id?: () -> bool

    def will_save_change_to_profile_id?: () -> bool

    def restore_profile_id!: () -> void

    def clear_profile_id_change: () -> void
  end
  include GeneratedAttributeMethods

  def profile_badge: () -> ProfileBadge
  def profile_badge=: (ProfileBadge?) -> ProfileBadge?
  def reload_profile_badge: () -> ProfileBadge?
  def build_profile_badge: (untyped) -> ProfileBadge
  def create_profile_badge: (untyped) -> ProfileBadge
  def create_profile_badge!: (untyped) -> ProfileBadge
  def profile: () -> Profile
  def profile=: (Profile?) -> Profile?
  def reload_profile: () -> Profile?
  def build_profile: (untyped) -> Profile
  def create_profile: (untyped) -> Profile
  def create_profile!: (untyped) -> Profile
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[ProfileBadgesProfile, top]
    include Enumerable[ProfileBadgesProfile]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[ProfileBadgesProfile, top]
  end
end
