# resolve-type-names: false

class ::SocialAnnouncement < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::SocialAnnouncement, ::SocialAnnouncement::ActiveRecord_Relation, ::Integer]

  module ::SocialAnnouncement::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer

    def event_id: () -> ::Integer

    def event_id=: (::Integer) -> ::Integer

    def event_id?: () -> bool

    def event_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def event_id_change: () -> [ ::Integer?, ::Integer? ]

    def event_id_will_change!: () -> void

    def event_id_was: () -> ::Integer?

    def event_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def event_id_previous_change: () -> ::Array[::Integer?]?

    def event_id_previously_was: () -> ::Integer?

    def event_id_before_last_save: () -> ::Integer?

    def event_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def event_id_in_database: () -> ::Integer?

    def saved_change_to_event_id: () -> ::Array[::Integer?]?

    def saved_change_to_event_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_event_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_event_id!: () -> void

    def clear_event_id_change: () -> void

    def event_id_before_type_cast: () -> ::Integer

    def event_id_for_database: () -> ::Integer

    def campaign: () -> ::String

    def campaign=: (::String) -> ::String

    def campaign?: () -> bool

    def campaign_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def campaign_change: () -> [ ::String?, ::String? ]

    def campaign_will_change!: () -> void

    def campaign_was: () -> ::String?

    def campaign_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def campaign_previous_change: () -> ::Array[::String?]?

    def campaign_previously_was: () -> ::String?

    def campaign_before_last_save: () -> ::String?

    def campaign_change_to_be_saved: () -> ::Array[::String?]?

    def campaign_in_database: () -> ::String?

    def saved_change_to_campaign: () -> ::Array[::String?]?

    def saved_change_to_campaign?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_campaign?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_campaign!: () -> void

    def clear_campaign_change: () -> void

    def campaign_before_type_cast: () -> ::String

    def campaign_for_database: () -> ::String

    def note: () -> ::String?

    def note=: (::String?) -> ::String?

    def note?: () -> bool

    def note_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def note_change: () -> [ ::String?, ::String? ]

    def note_will_change!: () -> void

    def note_was: () -> ::String?

    def note_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def note_previous_change: () -> ::Array[::String?]?

    def note_previously_was: () -> ::String?

    def note_before_last_save: () -> ::String?

    def note_change_to_be_saved: () -> ::Array[::String?]?

    def note_in_database: () -> ::String?

    def saved_change_to_note: () -> ::Array[::String?]?

    def saved_change_to_note?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_note?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_note!: () -> void

    def clear_note_change: () -> void

    def note_before_type_cast: () -> ::String?

    def note_for_database: () -> ::String?

    def published_at: () -> ::ActiveSupport::TimeWithZone?

    def published_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

    def published_at?: () -> bool

    def published_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def published_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def published_at_will_change!: () -> void

    def published_at_was: () -> ::ActiveSupport::TimeWithZone?

    def published_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def published_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def published_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def published_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def published_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def published_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_published_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_published_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_published_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_published_at!: () -> void

    def clear_published_at_change: () -> void

    def published_at_before_type_cast: () -> ::Time?

    def published_at_for_database: () -> ::Time?

    def created_by_id: () -> ::Integer

    def created_by_id=: (::Integer) -> ::Integer

    def created_by_id?: () -> bool

    def created_by_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def created_by_id_change: () -> [ ::Integer?, ::Integer? ]

    def created_by_id_will_change!: () -> void

    def created_by_id_was: () -> ::Integer?

    def created_by_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def created_by_id_previous_change: () -> ::Array[::Integer?]?

    def created_by_id_previously_was: () -> ::Integer?

    def created_by_id_before_last_save: () -> ::Integer?

    def created_by_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def created_by_id_in_database: () -> ::Integer?

    def saved_change_to_created_by_id: () -> ::Array[::Integer?]?

    def saved_change_to_created_by_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_created_by_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_created_by_id!: () -> void

    def clear_created_by_id_change: () -> void

    def created_by_id_before_type_cast: () -> ::Integer

    def created_by_id_for_database: () -> ::Integer

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::SocialAnnouncement::GeneratedAttributeMethods
  module ::SocialAnnouncement::GeneratedAliasAttributeMethods
    include ::SocialAnnouncement::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::SocialAnnouncement::GeneratedAliasAttributeMethods
  def texts: () -> ::SocialAnnouncementText::ActiveRecord_Associations_CollectionProxy
  def texts=: (::SocialAnnouncementText::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementText]) -> (::SocialAnnouncementText::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementText])
  def text_ids: () -> ::Array[::Integer]
  def text_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def target_platforms: () -> ::SocialAnnouncementTargetPlatform::ActiveRecord_Associations_CollectionProxy
  def target_platforms=: (::SocialAnnouncementTargetPlatform::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementTargetPlatform]) -> (::SocialAnnouncementTargetPlatform::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementTargetPlatform])
  def target_platform_ids: () -> ::Array[::Integer]
  def target_platform_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def media: () -> ::SocialAnnouncementMedia::ActiveRecord_Associations_CollectionProxy
  def media=: (::SocialAnnouncementMedia::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementMedia]) -> (::SocialAnnouncementMedia::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementMedia])
  def medium_ids: () -> ::Array[::Integer]
  def medium_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def posts: () -> ::SocialAnnouncementPost::ActiveRecord_Associations_CollectionProxy
  def posts=: (::SocialAnnouncementPost::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementPost]) -> (::SocialAnnouncementPost::ActiveRecord_Associations_CollectionProxy | ::Array[::SocialAnnouncementPost])
  def post_ids: () -> ::Array[::Integer]
  def post_ids=: (::Array[::Integer]) -> ::Array[::Integer]

  def event: () -> ::Event
  def event=: (::Event?) -> ::Event?
  def reload_event: () -> ::Event?
  def build_event: (?untyped) -> ::Event
  def create_event: (?untyped) -> ::Event
  def create_event!: (?untyped) -> ::Event
  def created_by: () -> ::User
  def created_by=: (::User?) -> ::User?
  def reload_created_by: () -> ::User?
  def build_created_by: (?untyped) -> ::User
  def create_created_by: (?untyped) -> ::User
  def create_created_by!: (?untyped) -> ::User

  module ::SocialAnnouncement::GeneratedAssociationMethods
    def media_attributes=: (Hash[untyped, untyped] | Array[Hash[untyped, untyped]]) -> void
  end
  include ::SocialAnnouncement::GeneratedAssociationMethods

  module ::SocialAnnouncement::GeneratedRelationMethods
  end

  class ::SocialAnnouncement::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::SocialAnnouncement]
    include ::SocialAnnouncement::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::SocialAnnouncement, ::Integer]
  end

  class ::SocialAnnouncement::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::SocialAnnouncement]
    include ::SocialAnnouncement::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::SocialAnnouncement, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SocialAnnouncement
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SocialAnnouncement]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SocialAnnouncement
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SocialAnnouncement]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SocialAnnouncement
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SocialAnnouncement]
    def reload: () -> ::Array[::SocialAnnouncement]

    def replace: (::Array[::SocialAnnouncement]) -> void
    def delete: (*::SocialAnnouncement | ::Integer) -> ::Array[::SocialAnnouncement]
    def destroy: (*::SocialAnnouncement | ::Integer) -> ::Array[::SocialAnnouncement]
    def <<: (*::SocialAnnouncement | ::Array[::SocialAnnouncement]) -> self
    def prepend: (*::SocialAnnouncement | ::Array[::SocialAnnouncement]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::SocialAnnouncementText < ::ApplicationRecord
end
class ::SocialAnnouncementText::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::SocialAnnouncementTargetPlatform < ::ApplicationRecord
end
class ::SocialAnnouncementTargetPlatform::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::SocialAnnouncementMedia < ::ApplicationRecord
end
class ::SocialAnnouncementMedia::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::SocialAnnouncementPost < ::ApplicationRecord
end
class ::SocialAnnouncementPost::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Event < ::ApplicationRecord
end
class ::User < ::ApplicationRecord
end
