# resolve-type-names: false

class ::SpeakersTalk < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::SpeakersTalk, ::SpeakersTalk::ActiveRecord_Relation, top]

  module ::SpeakersTalk::GeneratedAttributeMethods
    def speaker_id: () -> ::Integer

    def speaker_id=: (::Integer) -> ::Integer

    def speaker_id?: () -> bool

    def speaker_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def speaker_id_change: () -> [ ::Integer?, ::Integer? ]

    def speaker_id_will_change!: () -> void

    def speaker_id_was: () -> ::Integer?

    def speaker_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def speaker_id_previous_change: () -> ::Array[::Integer?]?

    def speaker_id_previously_was: () -> ::Integer?

    def speaker_id_before_last_save: () -> ::Integer?

    def speaker_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def speaker_id_in_database: () -> ::Integer?

    def saved_change_to_speaker_id: () -> ::Array[::Integer?]?

    def saved_change_to_speaker_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_speaker_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_speaker_id!: () -> void

    def clear_speaker_id_change: () -> void

    def speaker_id_before_type_cast: () -> ::Integer

    def speaker_id_for_database: () -> ::Integer

    def talk_id: () -> ::Integer

    def talk_id=: (::Integer) -> ::Integer

    def talk_id?: () -> bool

    def talk_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def talk_id_change: () -> [ ::Integer?, ::Integer? ]

    def talk_id_will_change!: () -> void

    def talk_id_was: () -> ::Integer?

    def talk_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def talk_id_previous_change: () -> ::Array[::Integer?]?

    def talk_id_previously_was: () -> ::Integer?

    def talk_id_before_last_save: () -> ::Integer?

    def talk_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def talk_id_in_database: () -> ::Integer?

    def saved_change_to_talk_id: () -> ::Array[::Integer?]?

    def saved_change_to_talk_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_talk_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_talk_id!: () -> void

    def clear_talk_id_change: () -> void

    def talk_id_before_type_cast: () -> ::Integer

    def talk_id_for_database: () -> ::Integer
  end
  include ::SpeakersTalk::GeneratedAttributeMethods
  module ::SpeakersTalk::GeneratedAliasAttributeMethods
    include ::SpeakersTalk::GeneratedAttributeMethods
  end
  include ::SpeakersTalk::GeneratedAliasAttributeMethods

  def speaker: () -> ::Speaker
  def speaker=: (::Speaker?) -> ::Speaker?
  def reload_speaker: () -> ::Speaker?
  def build_speaker: (?untyped) -> ::Speaker
  def create_speaker: (?untyped) -> ::Speaker
  def create_speaker!: (?untyped) -> ::Speaker
  def talk: () -> ::Talk
  def talk=: (::Talk?) -> ::Talk?
  def reload_talk: () -> ::Talk?
  def build_talk: (?untyped) -> ::Talk
  def create_talk: (?untyped) -> ::Talk
  def create_talk!: (?untyped) -> ::Talk

  module ::SpeakersTalk::GeneratedAssociationMethods
  end
  include ::SpeakersTalk::GeneratedAssociationMethods

  module ::SpeakersTalk::GeneratedRelationMethods
  end

  class ::SpeakersTalk::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::SpeakersTalk]
    include ::SpeakersTalk::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::SpeakersTalk, top]
  end

  class ::SpeakersTalk::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::SpeakersTalk]
    include ::SpeakersTalk::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::SpeakersTalk, top]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SpeakersTalk
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SpeakersTalk]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SpeakersTalk
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SpeakersTalk]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SpeakersTalk
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SpeakersTalk]
    def reload: () -> ::Array[::SpeakersTalk]

    def replace: (::Array[::SpeakersTalk]) -> void
    def delete: (*::SpeakersTalk | top) -> ::Array[::SpeakersTalk]
    def destroy: (*::SpeakersTalk | top) -> ::Array[::SpeakersTalk]
    def <<: (*::SpeakersTalk | ::Array[::SpeakersTalk]) -> self
    def prepend: (*::SpeakersTalk | ::Array[::SpeakersTalk]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Speaker < ::ApplicationRecord
end
class ::Talk < ::ApplicationRecord
end
