class User < ::ApplicationRecord
  extend ::_ActiveRecord_Relation_ClassMethods[::User, ::User::ActiveRecord_Relation, ::Integer]

  module GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def name: () -> ::String

    def name=: (::String) -> ::String

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ ::String?, ::String? ]

    def name_will_change!: () -> void

    def name_was: () -> ::String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> ::Array[::String?]?

    def name_previously_was: () -> ::String?

    def name_before_last_save: () -> ::String?

    def name_change_to_be_saved: () -> ::Array[::String?]?

    def name_in_database: () -> ::String?

    def saved_change_to_name: () -> ::Array[::String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def role: () -> ::String

    def role=: (::String) -> ::String

    def role?: () -> bool

    def role_changed?: () -> bool

    def role_change: () -> [ ::String?, ::String? ]

    def role_will_change!: () -> void

    def role_was: () -> ::String?

    def role_previously_changed?: () -> bool

    def role_previous_change: () -> ::Array[::String?]?

    def role_previously_was: () -> ::String?

    def role_before_last_save: () -> ::String?

    def role_change_to_be_saved: () -> ::Array[::String?]?

    def role_in_database: () -> ::String?

    def saved_change_to_role: () -> ::Array[::String?]?

    def saved_change_to_role?: () -> bool

    def will_save_change_to_role?: () -> bool

    def restore_role!: () -> void

    def clear_role_change: () -> void

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void
  end
  include GeneratedAttributeMethods
  def webpush_subscriptions: () -> ::WebpushSubscription::ActiveRecord_Associations_CollectionProxy
  def webpush_subscriptions=: (::WebpushSubscription::ActiveRecord_Associations_CollectionProxy | ::Array[::WebpushSubscription]) -> (::WebpushSubscription::ActiveRecord_Associations_CollectionProxy | ::Array[::WebpushSubscription])
  def webpush_subscription_ids: () -> ::Array[::Integer]
  def webpush_subscription_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def unread_announcements: () -> ::UnreadAnnouncement::ActiveRecord_Associations_CollectionProxy
  def unread_announcements=: (::UnreadAnnouncement::ActiveRecord_Associations_CollectionProxy | ::Array[::UnreadAnnouncement]) -> (::UnreadAnnouncement::ActiveRecord_Associations_CollectionProxy | ::Array[::UnreadAnnouncement])
  def unread_announcement_ids: () -> ::Array[::Integer]
  def unread_announcement_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def talk_bookmarks: () -> ::TalkBookmark::ActiveRecord_Associations_CollectionProxy
  def talk_bookmarks=: (::TalkBookmark::ActiveRecord_Associations_CollectionProxy | ::Array[::TalkBookmark]) -> (::TalkBookmark::ActiveRecord_Associations_CollectionProxy | ::Array[::TalkBookmark])
  def talk_bookmark_ids: () -> ::Array[::Integer]
  def talk_bookmark_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def profile_exchanges: () -> ::ProfileExchange::ActiveRecord_Associations_CollectionProxy
  def profile_exchanges=: (::ProfileExchange::ActiveRecord_Associations_CollectionProxy | ::Array[::ProfileExchange]) -> (::ProfileExchange::ActiveRecord_Associations_CollectionProxy | ::Array[::ProfileExchange])
  def profile_exchange_ids: () -> ::Array[::Integer]
  def profile_exchange_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def friends: () -> ::User::ActiveRecord_Associations_CollectionProxy
  def friends=: (::User::ActiveRecord_Associations_CollectionProxy | ::Array[::User]) -> (::User::ActiveRecord_Associations_CollectionProxy | ::Array[::User])
  def friend_ids: () -> ::Array[::Integer]
  def friend_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def talk_reminders: () -> ::TalkReminder::ActiveRecord_Associations_CollectionProxy
  def talk_reminders=: (::TalkReminder::ActiveRecord_Associations_CollectionProxy | ::Array[::TalkReminder]) -> (::TalkReminder::ActiveRecord_Associations_CollectionProxy | ::Array[::TalkReminder])
  def talk_reminder_ids: () -> ::Array[::Integer]
  def talk_reminder_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def authentication_provider_github: () -> ::AuthenticationProviderGithub?
  def authentication_provider_github=: (::AuthenticationProviderGithub?) -> ::AuthenticationProviderGithub?
  def build_authentication_provider_github: (?untyped) -> ::AuthenticationProviderGithub
  def create_authentication_provider_github: (untyped) -> ::AuthenticationProviderGithub
  def create_authentication_provider_github!: (untyped) -> ::AuthenticationProviderGithub
  def reload_authentication_provider_github: () -> ::AuthenticationProviderGithub?
  def authentication_provider_email_and_password: () -> ::AuthenticationProviderEmailAndPassword?
  def authentication_provider_email_and_password=: (::AuthenticationProviderEmailAndPassword?) -> ::AuthenticationProviderEmailAndPassword?
  def build_authentication_provider_email_and_password: (?untyped) -> ::AuthenticationProviderEmailAndPassword
  def create_authentication_provider_email_and_password: (untyped) -> ::AuthenticationProviderEmailAndPassword
  def create_authentication_provider_email_and_password!: (untyped) -> ::AuthenticationProviderEmailAndPassword
  def reload_authentication_provider_email_and_password: () -> ::AuthenticationProviderEmailAndPassword?
  def profile: () -> ::Profile?
  def profile=: (::Profile?) -> ::Profile?
  def build_profile: (?untyped) -> ::Profile
  def create_profile: (untyped) -> ::Profile
  def create_profile!: (untyped) -> ::Profile
  def reload_profile: () -> ::Profile?

  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::User::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::User, ::Integer]
    include ::Enumerable[::User]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::User::GeneratedRelationMethods
    include ::_ActiveRecord_Relation[::User, ::Integer]
  end
end
