class UsersController < ApplicationController
  include ApplicationHelper

  @user: User

  @events: Event::ActiveRecord_Relation

  @event_friends: untyped

  @profile: Profile

  @token: String?

  private def exchange_profile: (User user1, User user2) -> void
end
