class UsersController < ApplicationController
  @user: User

  @profile: Profile

  # TODO: In implementation, `@token` is surely an optional string. But steep does not support type-narrowing for
  #       instance variables.  Therefore it will cause type errors to give a type to this variable.
  # @token: String?
end
