class CloudflareApiClient
  @account_id: String
  @api_token: String

  def initialize: -> void
  def list_live_inputs: -> Hash[untyped, untyped]
  def create_live_input: (name: String) -> Hash[untyped, untyped]
  def retrieve_live_input: (String uid) -> Hash[untyped, untyped]
  def retrieve_live_input_videos: (String uid) -> Hash[untyped, untyped]
  def list_streams: -> Hash[untyped, untyped]
end
