# resolve-type-names: false

module ::SolidQueue
  class ::SolidQueue::Semaphore < ::SolidQueue::Record
    extend ::ActiveRecord::Base::ClassMethods[::SolidQueue::Semaphore, ::SolidQueue::Semaphore::ActiveRecord_Relation, ::Integer]

    module ::SolidQueue::Semaphore::GeneratedAttributeMethods
      def id: () -> ::Integer

      def id=: (::Integer) -> ::Integer

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer

      def id_for_database: () -> ::Integer

      def key: () -> ::String

      def key=: (::String) -> ::String

      def key?: () -> bool

      def key_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def key_change: () -> [ ::String?, ::String? ]

      def key_will_change!: () -> void

      def key_was: () -> ::String?

      def key_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def key_previous_change: () -> ::Array[::String?]?

      def key_previously_was: () -> ::String?

      def key_before_last_save: () -> ::String?

      def key_change_to_be_saved: () -> ::Array[::String?]?

      def key_in_database: () -> ::String?

      def saved_change_to_key: () -> ::Array[::String?]?

      def saved_change_to_key?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_key?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_key!: () -> void

      def clear_key_change: () -> void

      def key_before_type_cast: () -> ::String

      def key_for_database: () -> ::String

      def value: () -> ::Integer

      def value=: (::Integer) -> ::Integer

      def value?: () -> bool

      def value_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def value_change: () -> [ ::Integer?, ::Integer? ]

      def value_will_change!: () -> void

      def value_was: () -> ::Integer?

      def value_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def value_previous_change: () -> ::Array[::Integer?]?

      def value_previously_was: () -> ::Integer?

      def value_before_last_save: () -> ::Integer?

      def value_change_to_be_saved: () -> ::Array[::Integer?]?

      def value_in_database: () -> ::Integer?

      def saved_change_to_value: () -> ::Array[::Integer?]?

      def saved_change_to_value?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_value?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_value!: () -> void

      def clear_value_change: () -> void

      def value_before_type_cast: () -> ::Integer

      def value_for_database: () -> ::Integer

      def expires_at: () -> ::ActiveSupport::TimeWithZone

      def expires_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def expires_at?: () -> bool

      def expires_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def expires_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def expires_at_will_change!: () -> void

      def expires_at_was: () -> ::ActiveSupport::TimeWithZone?

      def expires_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def expires_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def expires_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def expires_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def expires_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def expires_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_expires_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_expires_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_expires_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_expires_at!: () -> void

      def clear_expires_at_change: () -> void

      def expires_at_before_type_cast: () -> ::Time

      def expires_at_for_database: () -> ::Time

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time
    end
    include ::SolidQueue::Semaphore::GeneratedAttributeMethods
    module ::SolidQueue::Semaphore::GeneratedAliasAttributeMethods
      include ::SolidQueue::Semaphore::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::SolidQueue::Semaphore::GeneratedAliasAttributeMethods

    module ::SolidQueue::Semaphore::GeneratedAssociationMethods
    end
    include ::SolidQueue::Semaphore::GeneratedAssociationMethods

    def self.available: () -> ::SolidQueue::Semaphore::ActiveRecord_Relation
    def self.expired: () -> ::SolidQueue::Semaphore::ActiveRecord_Relation

    module ::SolidQueue::Semaphore::GeneratedRelationMethods
      def available: () -> ::SolidQueue::Semaphore::ActiveRecord_Relation

      def expired: () -> ::SolidQueue::Semaphore::ActiveRecord_Relation
    end

    class ::SolidQueue::Semaphore::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::SolidQueue::Semaphore]
      include ::SolidQueue::Semaphore::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SolidQueue::Semaphore, ::Integer]
    end

    class ::SolidQueue::Semaphore::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::SolidQueue::Semaphore]
      include ::SolidQueue::Semaphore::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::SolidQueue::Semaphore, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidQueue::Semaphore
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidQueue::Semaphore]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidQueue::Semaphore
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidQueue::Semaphore]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SolidQueue::Semaphore
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SolidQueue::Semaphore]
      def reload: () -> ::Array[::SolidQueue::Semaphore]

      def replace: (::Array[::SolidQueue::Semaphore]) -> void
      def delete: (*::SolidQueue::Semaphore | ::Integer) -> ::Array[::SolidQueue::Semaphore]
      def destroy: (*::SolidQueue::Semaphore | ::Integer) -> ::Array[::SolidQueue::Semaphore]
      def <<: (*::SolidQueue::Semaphore | ::Array[::SolidQueue::Semaphore]) -> self
      def prepend: (*::SolidQueue::Semaphore | ::Array[::SolidQueue::Semaphore]) -> self
    end
  end
end

module ::SolidQueue
end
class ::SolidQueue::Record < ::ActiveRecord::Base
end
