class Announcement < ApplicationRecord
  # NOTE: This method has been declared manually because current rbs_rails does not support enum definitions.
  #       It should be removed if rbs_rails will support it.
  #       refs: https://github.com/pocke/rbs_rails/pull/268
  def self.published: () -> Announcement::ActiveRecord_Relation

  class ActiveRecord_Relation
    # NOTE: This method has been declared manually because current rbs_rails does not support enum definitions.
    #       It should be removed if rbs_rails will support it.
    #       refs: https://github.com/pocke/rbs_rails/pull/268
    def published: () -> self

    # NOTE: Added by ActionText
    def with_rich_text_content_and_embeds: () -> self
  end
end
