class User < ApplicationRecord
  # NOTE: This method has been declared manually because current rbs_rails does not support enum definitions.
  #       It should be removed if rbs_rails will support it.
  #       refs: https://github.com/pocke/rbs_rails/pull/268
  def organizer?: () -> bool
  def participant?: () -> bool

  def have_unread_announcements?: () -> bool
  def destroy_talk_bookmark_with_reminder!: (Integer id) -> bool

  class ActiveRecord_Relation
    # NOTE: Added by kaminari
    def page: (untyped) -> self
    def per: (Integer) -> self
  end
end
