class Admin::SignageSchedulesController < AdminController
  @signage: untyped

  @signage_schedule: untyped

  def new: () -> untyped

  def create: () -> untyped

  def edit: () -> untyped

  def update: () -> untyped

  def destroy: () -> untyped

  private

  def signage_schedule_params: () -> untyped

  def zoned_signage_schedule_params: () -> untyped
end
