class Admin::SignageScheduleAssignsController < AdminController
  @signage_schedule_assign: untyped

  @signage_schedules: untyped

  @signage_panels: untyped

  def new: () -> untyped

  def create: () -> untyped

  def destroy: () -> untyped

  private

  def signage_schedule_assign_params: () -> untyped
end
