class Admin::SignageDeviceAssignsController < AdminController
  @signage_device_assign: untyped

  @signage_devices: untyped

  @signage_panels: untyped

  def new: () -> untyped

  def create: () -> untyped

  def destroy: () -> untyped

  private

  def signage_device_assign_params: () -> untyped
end
