class Admin::UsersController < AdminController
  def index: () -> untyped

  def show: () -> untyped

  def edit: () -> untyped

  def update: () -> untyped

  private

  def user_params: () -> untyped
end
