class Profile < ApplicationRecord
  belongs_to :user
  has_many :profile_badges_profiles, dependent: :delete_all
  has_many :profile_badges, through: :profile_badges_profiles

  # Variants are generated by a job when an image is attached, so that the
  # first page to show one does not have to, and by `bin/rails
  # image_variants:backfill` for images attached before.
  has_many_attached :images do |attachable|
    # The header icon. Same transformations as the inline ones it replaces, so
    # the variants already generated keep being used.
    attachable.variant :icon, resize_to_limit: [50, 50], preprocessed: true
    # Friend lists, shown at 80px. Three times that, for phone screens.
    attachable.variant :thumb, resize_to_limit: [240, 240], preprocessed: true
  end

  # The provider passes the URL: it is the one that knows where its avatars
  # live, and this way Profile does not reach back into a provider of its own.
  #
  # @rbs url: String?
  # @rbs source: String
  # @rbs return: void
  def ensure_image_from(url, source:)
    return if url.blank?

    profile_image = URI.open(url) # standard:disable Security/Open
    m = Marcel::Magic.by_magic profile_image
    images.attach(io: profile_image, filename: "#{source}.#{m.subtype}")
  end
end
