name: CI on Rails edge

on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
env:
  BUNDLE_GEMFILE: gemfiles/rails_edge.gemfile
  RAILS_ENV: test
  TZ: "Asia/Tokyo"
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/conference_app_test
jobs:
  build:
    name: CI on Rails edge
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4-bookworm
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: conference_app_test
      redis:
        image: redis:7.2-bookworm
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: bundle exec rails db:schema:load
      - run: bundle exec i18n export
      - run: pnpm build
      - run: bundle exec rails tailwindcss:build
      - run: bundle exec rspec
